#!/bin/sh

set -e

case "$1" in
-dumpmachine)
  echo @GNU_TRIPLET@
  exit 0
  ;;
esac

exec gcc -march=@GCC_ARCH@ -m@GCC_MULTILIB@ \
         --no-sysroot-suffix -B/usr/lib/gcc/@GNU_TRIPLET@/@GCC_VERSION@ \
         -isystem=/usr/include/@GNU_TRIPLET@ "$@"
